version: '3.8'

services:
  # Production Netanya Incident Service
  incident-service:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: netanya-incident-service-prod
    ports:
      - "8000:8000"
    environment:
      - DEBUG_MODE=false
      - LOG_LEVEL=INFO
      - ENVIRONMENT=production
      - PORT=8000
      - SHAREPOINT_ENDPOINT=${SHAREPOINT_ENDPOINT}
    restart: unless-stopped
    networks:
      - netanya-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Production Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: netanya-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/ssl:/etc/nginx/ssl:ro
    depends_on:
      - incident-service
    networks:
      - netanya-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'

networks:
  netanya-network:
    driver: bridge
    name: netanya-production
