apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: netanya-incident-service-staging
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/memory: "512Mi"
        run.googleapis.com/cpu: "1"
        run.googleapis.com/min-instances: "0"
        run.googleapis.com/max-instances: "10"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: ghcr.io/motis10/incident-service:develop
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "staging"
        - name: DEBUG_MODE
          value: "true"
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: PORT
          value: "8000"
        - name: SHAREPOINT_ENDPOINT
          value: "https://staging-sharepoint.example.com/api"
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 10
  traffic:
  - percent: 100
    latestRevision: true
