app:
  name: "Netanya Incident Service"
  version: "1.0.0"
  environment: "development"
  debug_mode: true
  log_level: "DEBUG"
  port: 8000

sharepoint:
  endpoint: "http://mock-sharepoint:8080/api/incidents"
  timeout: 30
  retry_attempts: 3
  mock_mode: true

logging:
  level: "DEBUG"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: null
  console: true

cors:
  allow_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
    - "http://dev.netanya-incident.local"
  allow_credentials: true
  allow_methods:
    - "GET"
    - "POST"
    - "OPTIONS"
  allow_headers:
    - "*"

rate_limiting:
  api_requests_per_minute: 60
  health_requests_per_minute: 120

security:
  enforce_https: false
  include_docs: true
  cors_permissive: true

features:
  health_monitoring: true
  request_logging: true
  error_tracking: true
  metrics_collection: false

development:
  auto_reload: true
  show_sql: false
  mock_external_services: true
  verbose_errors: true
