app:
  name: "Netanya Incident Service"
  version: "1.0.0"
  environment: "production"
  debug_mode: false
  log_level: "INFO"
  port: 8000

sharepoint:
  endpoint: "${SHAREPOINT_ENDPOINT}"
  timeout: 60
  retry_attempts: 5
  mock_mode: false

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "/var/log/netanya-incident-service.log"
  console: true

cors:
  allow_origins:
    - "https://netanya.muni.il"
    - "https://services.netanya.muni.il"
  allow_credentials: false
  allow_methods:
    - "GET"
    - "POST"
    - "OPTIONS"
  allow_headers:
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"

rate_limiting:
  api_requests_per_minute: 30
  health_requests_per_minute: 60

security:
  enforce_https: true
  include_docs: false
  cors_permissive: false

features:
  health_monitoring: true
  request_logging: true
  error_tracking: true
  metrics_collection: true

production:
  workers: 4
  max_connections: 1000
  keepalive: 2
  log_access: true
  log_errors: true
